### PR TITLE
Add Pop!_OS as a compatible distro.

### LINKED ISSUE #66: Recognize Pop!_OS as a compatible distro.

### PR DESCRIPTION
**Pull request by jtagcat**
Singed-off-by: Rasmus Kallas <eid-09e1392f@c7.ee>

Tested successfully on Pop!_OS 18.04, 19.10 and 20.04.

Closes #66

### CODE REVIEW

**Comment by jtagcat** [comment]
Closes #66

**Comment by kristelmerilain** [comment]
Please move eoan to make fail, beacause eoan end of life is july 2020.

**Comment by jtagcat** [comment]
Removed, eoan. Requesting review.

**Comment by jtagcat** [comment]
Now also tested on 20.04.

image

**Pull request merged**
